
# 数据格式:
# {
#   "navs": [{
#     name,       路由命名
#     title,      导航标题
#     path,       导航链接
#     router,     模板路径
#     alias,      别名
#     redirect,   重定向（简洁使用，仅接受name）
#   },
#    ...
#   ]
# }


# ROUTER_PATH = '../views`/'

[[navs]]
name = "vue"
title = "Vue示例"
path = "/vue"
router = "vue"

[[navs]]
name = "layout"
title = "Layout"
path = "/layout"
router = "layout/index"
redirect = "layout1"
  [[navs.child]]
  name = "layout1"
  title = "第一个布局"
  path = "layout1"
  router = "layout/layout1"
  [[navs.child]]
  name = "layout2"
  title = "第二个布局"
  path = "layout2"
  router = "layout/layout2"
  [[navs.child]]
  name = "layout3"
  title = "第三个布局"
  path = "layout3"
  router = "layout/layout3"
  [[navs.child]]
  name = "layout4"
  title = "第四个布局"
  path = "layout4"
  router = "layout/layout4"

[[navs]]
name = "flex"
title = "FLEX"
path = "/flex"
router = "third"

[[navs]]
name = "limi"
title = "厘米例子"
path = "/limi"
router = "limi"


[[navs]]
name = "mind"
title = "MIND"
path = "/mind"
router = "mind/index"
alias = "/"
  [navs.redirect]
  name = "mind1"
  [[navs.child]]
  name = "mind1"
  title = "日历"
  path = "mind1"
  router = "mind/mind_1"
  [[navs.child]]
  name = "shadow"
  title = "多重投影"
  path = "shadow"
  router = "mind/shadow"
  [[navs.child]]
  name = "girl"
  title = "GIRL"
  path = "girl"
  router = "mind/girl"
  [[navs.child]]
  name = "linear_gradient"
  title = "条纹"
  path = "linear-gradient"
  router = "mind/linear_gradient"
  [[navs.child]]
  name = "vuex"
  title = "VUEX"
  path = "VUEX"
  router = "vuex"
