
# 数据格式可当做:
# {
#   "navs": [{
#     name,       路由命名
#     title,      导航标题
#     path,       导航链接
#     router,     模板路径
#     do          是否完成
#   },
#    ...
#   ]
# }


# ROUTER_PATH = '../router/'

[[navs]]
name = "page"
title = "ELEMENT"
path = "/page"
router = "page"

[[navs]]
name = "flex"
title = "FLEX"
path = "/flex"
router = "third"

[[navs]]
name = "limi"
title = "厘米例子"
path = "/limi"
router = "limi"

[[navs]]
name = "girl"
title = "GIRL"
path = "/girl"
router = "girl"

[[navs]]
name = "mind"
title = "MIND"
path = "/mind"
router = "mind"
redirect = "child"
  [[navs.child]]
  name = "child"
  title = "日历"
  path = "child"
  router = "second"