
# 数据格式可当做:
# {
#   "navs": [{
#     title,      导航标题
#     path,       导航链接
#     component,  路由模板，默认为components的子目录下的index.vue
#     do          是否完成
#   },
#    ...
#   ]
# }

[[navs]]
title = "PAGE"
path = "/page"
component = "page/index"
do = true

[[navs]]
title = "FLEX"
path = "/flex"
component = "flex/index"
# component = "flex/second"
do = true

[[navs]]
title = "厘米例子"
path = "/limi"
component = "limi/index"
do = true

[[navs]]
title = "待定"
do = false