
# 数据格式可当做:
# {
#   "navs": [{
#     title,      导航标题
#     path,       导航链接
#     router,     模板路径
#     do          是否完成
#   },
#    ...
#   ]
# }


# ROUTER_PATH = '../router/'

[[navs]]
title = "PAGE"
path = "/page"
router = "page"
do = true

[[navs]]
title = "FLEX"
path = "/flex"
router = "third"
# router = "flex/second"
do = true

[[navs]]
title = "厘米例子"
path = "/limi"
router = "limi"
do = true

[[navs]]
title = "girl"
path = "/girl"
router = "girl"
do = true

[[navs]]
title = "mind"
path = "/mind"
router = "mind"
do = true