
# 数据格式:
# {
#   "navs": [{
#     name,       路由命名
#     title,      导航标题
#     path,       导航链接
#     router,     模板路径
#     alias,      别名
#     redirect,   重定向（简洁使用，仅接受name）
#   },
#    ...
#   ]
# }


# ROUTER_PATH = '../router/'

[[navs]]
name = "page"
title = "ELEMENT"
path = "/page"
router = "page"

[[navs]]
name = "flex"
title = "FLEX"
path = "/flex"
router = "third"

[[navs]]
name = "limi"
title = "厘米例子"
path = "/limi"
router = "limi"


[[navs]]
name = "mind"
title = "MIND"
path = "/mind"
router = "mind/index"
redirect = "mind1"  
alias = "/"

# 当点击mind标签时，默认到mind1页面
# 子路由中的path不含/
  [[navs.child]]
  name = "mind1"
  title = "日历"
  path = "mind1"
  router = "mind/mind_1"

  [[navs.child]]
  name = "shadow"
  title = "多重投影"
  path = "shadow"
  router = "mind/shadow"

  [[navs.child]]
  name = "girl"
  title = "GIRL"
  path = "girl"
  router = "mind/girl"

  [[navs.child]]
  name = "lowbeecss"
  title = "玩玩CSS"
  path = "lowcss"
  router = "mind/mind_2"

  [[navs.child]]
  name = "linear_gradient"
  title = "条纹"
  path = "linear-gradient"
  router = "mind/linear_gradient"