
# 数据格式可当做:
# {
#   "navs": [{
#     title,      导航标题
#     path,       导航链接
#     router,  路由模板，默认为routers的子目录下的index.vue
#     do          是否完成
#   },
#    ...
#   ]
# }


# ROUTER_PATH = '../router/'

[[navs]]
title = "PAGE"
path = "/page"
router = "page"
do = true

[[navs]]
title = "FLEX"
path = "/flex"
router = "flex"
# router = "flex/second"
do = true

[[navs]]
title = "厘米例子"
path = "/limi"
router = "limi"
do = true

[[navs]]
title = "HelloKitty"
path = "/kitty"
router = "kitty"
do = true