[[path]]
title = "PAGE"
path = "/page"
component = "page/index"
do = true

[[path]]
title = "FLEX"
path = "/flex"
# component = "flex/index"
# component = "flex/second"
component = "flex/third"
do = true

[[path]]
title = "厘米例子"
path = "/limi"
component = "limi/index"
do = true

[[path]]
title = "待定"
do = false